"""empty message

Revision ID: 22c327c7d53d
Revises: e3abae8f1789
Create Date: 2019-10-26 09:54:07.437272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c327c7d53d'
down_revision = 'e3abae8f1789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'currency', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency', type_='foreignkey')
    op.drop_column('currency', 'user_id')
    # ### end Alembic commands ###
