"""add new relationship: currency_default

Revision ID: 38325cee7819
Revises: 56e5e401efcf
Create Date: 2019-11-09 17:46:03.589225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38325cee7819'
down_revision = '56e5e401efcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currency_default_choice', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'currency', ['currency_default_choice'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'currency_default_choice')
    op.add_column('currency', sa.Column('default', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
