"""add new relationship: default_currency

Revision ID: 42b0e70c96e8
Revises: 38325cee7819
Create Date: 2019-11-09 17:56:15.577229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b0e70c96e8'
down_revision = '38325cee7819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currency_default_choice', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'currency', ['currency_default_choice'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'currency_default_choice')
    op.add_column('currency', sa.Column('default', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
