"""expenses and currency

Revision ID: 68bb61b4eae7
Revises: cede303d8e0d
Create Date: 2019-10-15 20:30:02.383060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bb61b4eae7'
down_revision = 'cede303d8e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('abr', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('abr')
    )
    op.create_index(op.f('ix_currency_abr'), 'currency', ['abr'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_buy', sa.DateTime(), nullable=True),
    sa.Column('product', sa.String(length=140), nullable=True),
    sa.Column('category', sa.String(length=140), nullable=True),
    sa.Column('freq', sa.NullType(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Numeric(precision=2), nullable=True),
    sa.Column('currency', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_data_buy'), 'expenses', ['data_buy'], unique=False)
    op.create_index(op.f('ix_expenses_product'), 'expenses', ['product'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_product'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_data_buy'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_currency_abr'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
