"""empty message

Revision ID: 6c2ce9bcb347
Revises: 
Create Date: 2020-02-16 15:01:52.217866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2ce9bcb347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_cat')
    op.create_unique_constraint('_user_id_name', 'category', ['user_id', 'name'])
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.add_column('subwallet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subwallet', 'user', ['user_id'], ['id'])
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_foreign_key(None, 'wallet_subwallet', 'subwallet', ['subwallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_subwallet', type_='foreignkey')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_constraint(None, 'subwallet', type_='foreignkey')
    op.drop_column('subwallet', 'user_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint('_user_id_name', 'category', type_='unique')
    op.create_table('transaction_cat',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='transaction_cat_category_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_cat_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', 'category_id', name='transaction_cat_pkey')
    )
    # ### end Alembic commands ###
