"""empty message

Revision ID: e3abae8f1789
Revises: f4cf6e4c8cb9
Create Date: 2019-10-17 21:49:32.343429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3abae8f1789'
down_revision = 'f4cf6e4c8cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expenseDate', sa.DateTime(), nullable=True),
    sa.Column('product', sa.String(length=140), nullable=True),
    sa.Column('category', sa.String(length=140), nullable=True),
    sa.Column('freq', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Numeric(precision=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_category'), 'expense', ['category'], unique=False)
    op.create_index(op.f('ix_expense_expenseDate'), 'expense', ['expenseDate'], unique=False)
    op.create_index(op.f('ix_expense_product'), 'expense', ['product'], unique=False)
    op.create_index(op.f('ix_expense_user_id'), 'expense', ['user_id'], unique=False)
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_index('ix_expenses_data_buy', table_name='expenses')
    op.drop_index('ix_expenses_product', table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_buy', sa.DATETIME(), nullable=True),
    sa.Column('product', sa.VARCHAR(length=140), nullable=True),
    sa.Column('category', sa.VARCHAR(length=140), nullable=True),
    sa.Column('freq', sa.VARCHAR(length=64), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=2), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_product', 'expenses', ['product'], unique=False)
    op.create_index('ix_expenses_data_buy', 'expenses', ['data_buy'], unique=False)
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.drop_index(op.f('ix_expense_user_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_product'), table_name='expense')
    op.drop_index(op.f('ix_expense_expenseDate'), table_name='expense')
    op.drop_index(op.f('ix_expense_category'), table_name='expense')
    op.drop_table('expense')
    # ### end Alembic commands ###
