"""empty message

Revision ID: f4cf6e4c8cb9
Revises: 68bb61b4eae7
Create Date: 2019-10-15 20:37:52.850969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cf6e4c8cb9'
down_revision = '68bb61b4eae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_buy', sa.DateTime(), nullable=True),
    sa.Column('product', sa.String(length=140), nullable=True),
    sa.Column('category', sa.String(length=140), nullable=True),
    sa.Column('freq', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Numeric(precision=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_data_buy'), 'expenses', ['data_buy'], unique=False)
    op.create_index(op.f('ix_expenses_product'), 'expenses', ['product'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_product'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_data_buy'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
