"""add Currency.default

Revision ID: fab0246549ef
Revises: 90618ce27ef7
Create Date: 2019-11-08 19:58:37.117430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab0246549ef'
down_revision = '90618ce27ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('default', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'default')
    # ### end Alembic commands ###
